test: fix e2e test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -63,9 +63,7 @@ jobs:
             /root/project/cc-test-reporter before-build
             cd /js-base-image/packages/project && npm run test:ci
             # upload test report to Code Climate using `after-build`
-            if [ -z "$NOT_DEPLOY_COV_REPORT" ]; then
-              cd /js-base-image/ && /root/project/cc-test-reporter after-build --coverage-input-type lcov --exit-code $? # Providing this will prevent sending test coverage results for failed tests.
-            fi
+            cd /js-base-image/ && /root/project/cc-test-reporter after-build --coverage-input-type lcov --exit-code $? # Providing this will prevent sending test coverage results for failed tests.
       - store_test_results:
           path: /js-base-image/coverage/
       - store_artifacts:
