fix: full path

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -69,15 +69,14 @@ jobs:
     steps:
       - checkout
       - run:
-          name: Copy anki dir under js-base-image for testing
+          name: Copy project dir under js-base-image for testing
           command: |
-            mkdir -p /js-base-image/packages/anki
-            cp -r . /js-base-image/packages/anki/
+            mkdir -p /js-base-image/packages/project
+            cp -r . /js-base-image/packages/project/
       # - run: pwd
       - run:
           name: Setup Code Climate test-reporter
           command: |
-            pwd
             # download test reporter as a static binary
             curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > /root/project/cc-test-reporter
             chmod +x /root/project/cc-test-reporter
@@ -86,9 +85,11 @@ jobs:
           command: |
             # notify Code Climate of a pending test report using `before-build`
             /root/project/cc-test-reporter before-build
-            cd /js-base-image/packages/anki && npm run test:ci
+            cd /js-base-image/packages/project && npm run test:ci
             # upload test report to Code Climate using `after-build`
-            cd /js-base-image/ && /root/project/cc-test-reporter after-build --coverage-input-type lcov --exit-code $? # Providing this will prevent sending test coverage results for failed tests.
+            if [ -z "$PUSH_ONLY" ]; then
+              cd /js-base-image/ && /root/project/cc-test-reporter after-build --coverage-input-type lcov --exit-code $? # Providing this will prevent sending test coverage results for failed tests.
+            fi
       # - run: ls -al /js-base-image/
       - store_test_results:
           path: /js-base-image/coverage/
